import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '@/styles/global.scss';
import '@/config/configureMobX';
import { RootStoreProvider } from '@/store';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const robotoFont = localFont({
  src: [
    {
      path: '../assets/fonts/Roboto-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Roboto-SemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Roboto-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Roboto-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={robotoFont.className}>
        <div id="root">
          <RootStoreProvider>{children}</RootStoreProvider>
        </div>
      </body>
    </html>
  );
}
